FROM        jamesnesbitt/wunder-nginx
MAINTAINER  james.nesbitt@wunderkraut.com

### NGINX --------------------------------------------------------------------

# Use new nginx vhost conf for the d8 project web-root
#
ADD etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

### /NGINX -------------------------------------------------------------------
