FROM        jamesnesbitt/wunder-nginx
MAINTAINER  james.nesbitt@wunderkraut.com

### NGINX --------------------------------------------------------------------

# Use new nginx vhost confs
#
# This new conf send connections to one of three fpm servers
#
ADD etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

### /NGINX -------------------------------------------------------------------
